// Items not defined here that return a negative or 0 value when processing a
// stuck function will be added to /log/reports/struck_damage for review, when
// they have been verified to work correctly the file path should be added here.

#define STRUCK_REVIEWED ({ \
    "/d/token_hunt/obj/high/nightydsp", \
    "/d/token_hunt/obj/high/dragonrobe", \
    "/d/token_hunt/obj/high/wolfg", \
    "/d/token_hunt/obj/low/darkgem_shield", \
    "/d/token_hunt/obj/low/rainbowbangles", \
    "/d/token_hunt/obj/low/rubytalongaunt", \
    "/d/token_hunt/obj/mid/chainedovercoat", \
    "/d/token_hunt/obj/mid/forestarmor", \
    "/d/token_hunt/obj/mid/glitteringarmor", \
    "/d/token_hunt/obj/mid/ogregauntlets", \
    "/d/token_hunt/obj/mid/paingreaves", \
    "/d/token_hunt/obj/mid/seraphimarmor", \
    "/d/islands/serakii/obj/hound_robe", \
    "/d/islands/serakii/obj/legion_bracers", \
    "/d/islands/serakii/obj/hound_bracers", \
    "/d/islands/serakii/obj/legion_cassock", \
    "/d/islands/serakii/obj/moon_plate", \
    "/d/islands/serakii/obj/dragonrobes", \
    "/d/token_hunt/obj/mid/goldenstagcloth", \
    "/d/token_hunt/obj/mid/akaboots", \
    "/d/dagger/ogres/obj/doubletflames", \
    "/d/dagger/ogres/obj/malar_studded", \
    "/d/dagger/ogres/obj/sune_studded", \
    "/d/islands/elf/obj/scale_mail", \
    "/d/barriermnts/lothwaite/obj/ethereal_bplate", \
    "/d/barriermnts/lothwaite/obj/ghostboots", \
    "/d/barriermnts/lothwaite/obj/ghostsandals", \
    "/d/barriermnts/lothwaite/obj/torc", \
    "/d/antioch/jarmila/obj/vashapride", \
    "/d/antioch/ruins/obj/ebony_armor", \
    "/d/magic/obj/shields/callamir", \
    "/d/magic/obj/shields/cevahir", \
    "/d/magic/obj/shields/jarmila", \
    "/d/magic/obj/shields/khyron", \
    "/d/magic/obj/shields/kismet", \
    "/d/magic/obj/shields/kreysneothosies", \
    "/d/magic/obj/shields/lord_shadow", \
    "/d/magic/obj/shields/lysara", \
    "/d/magic/obj/shields/nilith", \
    "/d/magic/obj/shields/nimnavanon", \
    "/d/magic/obj/shields/seija", \
    "/d/magic/obj/shields/the_faceless_one", \
    "/d/islands/argentrock/obj/shd_bskeletal", \
    "/d/islands/argentrock/obj/shd_glassy", \
    "/d/islands/argentrock/obj/shd_gskeletal", \
    "/d/islands/common/eldebaro/ob/ebon_reflector", \
    "/d/islands/common/eldebaro/ob/shroud_of_darkness", \
    "/d/shadow/room/githyanki/obj/obsidion_vambraces", \
    "/d/islands/common/obj/new/e_chain", \
    "/d/islands/common/obj/new/flameguards", \
    "/d/islands/common/obj/new/p_mail", \
    "/d/islands/common/obj/new/shield", \
    "/d/islands/common/obj/new/shimmeringcape2", \
    "/d/islands/common/obj/new/snakebracers", \
    "/d/islands/common/obj/new/waveguards", \
    "/d/islands/common/obj/new/windguards", \
    "/d/attaya/obj/aut_armor", \
    "/d/attaya/obj/azure", \
    "/d/attaya/obj/shimmeringcape", \
    "/d/attaya/obj/silkdrape", \
    "/d/attaya/obj/silkvest", \
    "/d/attaya/senund/obj/darkrobe", \
    "/d/deku/hhouse/ob/azloths_blessing", \
    "/d/deku/hhouse/ob/heart_of_talos", \
    "/d/deku/hhouse/ob/lathanders_dawn", \
    "/d/deku/hhouse/ob/shroud_of_the_impaler", \
    "/d/islands/common/obj/harbinger", \
    "/d/underdark/lower/dragon/obj/barrier", \
    "/d/underdark/lower/dragon/obj/shadowdancer", \
    "/d/islands/common/obj/shimmeringcape2", \
    "/d/deku/armours/brobe", \
    "/d/deku/armours/priest_robe", \
    "/d/deku/armours/robe", \
    "/d/islands/elf/obj/bracers", \
    "/d/islands/elf/obj/shield", \
    "/d/islands/elf/obj/v_gloves", \
    "/d/dagger/derro/obj/shield", \
    "/d/dagger/marsh/tower/obj/shadowbracers", \
    "/d/dagger/marsh/tower/obj/castershoes", \
    "/d/islands/coralsea/obj/coralscape", \
    "/realms/nuwisha/obj/iceaura2", \
    "/d/islands/dallyh/marsh/obj/frobe", \
    "/d/islands/dallyh/forest/obj/rosebodice", \
    "/d/atoyatl/tecqumin/obj/poncho", \
    "/d/atoyatl/tecqumin/obj/poncho_greater", \
    "/d/atoyatl/tecqumin/obj/kilt", \
    "/d/atoyatl/tecqumin/obj/kilt_greater", \
    "/d/barriermnts/lothwaite/obj/ethereal_bracers", \
    "/realms/kismet/obj/rewards/k_balurhat", \
    "/realms/kismet/obj/rewards/moontiara", \
    "/realms/kismet/obj/rewards/r_orchid", \
    "/d/shadow/room/farm/obj/petal_buckler", \
    "/d/underdark/mines/obj/dragonmask", \
    "/d/underdark/mines/obj/gnorobe", \
    "/d/laerad/lgnolls/obj/gnollbarding", \
    "/d/laerad/outpost/obj/torm_shield", \
    "/d/laerad/outpost/obj/torm_scalemail", \
    "/d/islands/pirates/obj/newcoat", \
    "/d/islands/pirates/obj/redcoat", \
})
